### ISSUE TITLE
npm audit show vulnerable package

### ISSUE THREAD

**Issue by jrcastillo** [derrickpelletier/geohash-poly#18]
I installed the package and now npm show me this warning about a vulnerable package included in the dependencies. 
![screenshot from 2019-01-28 17-18-31](https://user-images.githubusercontent.com/9206779/51870341-4761de80-2321-11e9-8922-0f1eb315e9b4.png)

Probably it just to upgrade a package. I think I can make a PR for this.

**Comment by derrickpelletier** [comment]
Thanks for your PR, just released in `0.6.0`
